<a href="https://colab.research.google.com/github/phanducminh201/Sort_Algorithm/blob/main/Sort_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTING THE LIBRARIES**

In [ ]:
import numpy as np
import copy as cp
import statistics as st

# **SELECTION SORT**

In [ ]:
#sắp xếp chọn theo giá trị lớn nhất
B = [9,8,7,6,5,4,3,2,1]
print(B)

def tim_vt_max(mang, vt):
  indx = vt
  for i in range(0, vt):
    if mang[i] > mang[indx]:
      indx = i
  return indx


M = len(B)
vt_batdau = M-1
while (vt_batdau > 0):
  max_id = tim_vt_max(B, vt_batdau)
  B[vt_batdau], B[max_id] = B[max_id], B[vt_batdau]
  vt_batdau -= 1
  print(*B)
print(*B)

[9, 8, 7, 6, 5, 4, 3, 2, 1]
1 8 7 6 5 4 3 2 9
1 2 7 6 5 4 3 8 9
1 2 3 6 5 4 7 8 9
1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9


In [ ]:
#sap xep chon theo gia tri min (tang dan)
B = [1,3,9,2,5,10,7,15,1,8]
print(B)

def tim_vt_min(mang, vt):
  indx = vt
  print("vtbd=", indx)
  for i in range(0, vt):
    if mang[i] > mang[indx]:
      indx = i
  return indx

M = len(B)
vt_bd = M - 1
while(vt_bd > 0):
  min_indx = tim_vt_min(B, vt_bd)
  B[min_indx], B[vt_bd] = B[vt_bd], B[min_indx]
  vt_bd -= 1
  print(*B)
print(*B)

[1, 3, 9, 2, 5, 10, 7, 15, 1, 8]
vtbd= 9
1 3 9 2 5 10 7 8 1 15
vtbd= 8
1 3 9 2 5 1 7 8 10 15
vtbd= 7
1 3 8 2 5 1 7 9 10 15
vtbd= 6
1 3 7 2 5 1 8 9 10 15
vtbd= 5
1 3 1 2 5 7 8 9 10 15
vtbd= 4
1 3 1 2 5 7 8 9 10 15
vtbd= 3
1 2 1 3 5 7 8 9 10 15
vtbd= 2
1 1 2 3 5 7 8 9 10 15
vtbd= 1
1 1 2 3 5 7 8 9 10 15
1 1 2 3 5 7 8 9 10 15


In [ ]:
#sắp xếp chọn theo giá trị nhỏ nhất (giảm dần)
C = [1,3,5,7,9,11,13,15]

def tim_vt_min(mang, vt):
	idx = vt
	for i in range(vt, len(mang)):
		if mang[i] > mang[idx]:
			idx = i
	return idx


N = len(C)
vt_batdau = 0
print(*C)
while(vt_batdau < N-1):
  min_id = tim_vt_min(C,vt_batdau)
  C[vt_batdau], C[min_id] = C[min_id], C[vt_batdau]
  vt_batdau +=1
  print(*C)
print(*C)

1 3 5 7 9 11 13 15
15 3 5 7 9 11 13 1
15 13 5 7 9 11 3 1
15 13 11 7 9 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1


In [ ]:
#sắp xếp chọn theo giá trị lớn nhất (giảm dần)
C = [1,3,5,7,9,11,13,15]

def tim_vt_max(mang, vt): #vt = M-1
  indx = vt
  for i in range(0, vt):
    if mang[i] < mang[indx]:
      indx = i
  return indx


M = len(C)
vt_batdau = M-1
while (vt_batdau > 0):
  max_id = tim_vt_max(C, vt_batdau)
  C[vt_batdau], C[max_id] = C[max_id], C[vt_batdau]
  vt_batdau -= 1
  print(*C)
print(*C)

15 3 5 7 9 11 13 1
15 13 5 7 9 11 3 1
15 13 11 7 9 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1
15 13 11 9 7 5 3 1


# **BUBBLE SORT**

In [ ]:
C = [5, 3, 8, 4, 6]

#sắp xếp nổi bọt
def sxnb(mang):
  tmp = cp.copy(mang)
  for i in range(len(tmp)-1):
    print("i=", i)
    for j in range(i+1, len(tmp)):
      if mang[i] > mang[j]:
        mang[i], mang[j] = mang[j], mang[i]
        print(*mang)
  return mang

In [ ]:
print(C)
sxnb(C)

[5, 3, 8, 4, 6]
i= 0
3 5 8 4 6
i= 1
3 4 8 5 6
i= 2
3 4 5 8 6
i= 3
3 4 5 6 8


[3, 4, 5, 6, 8]

# **INSERTION SORT**

In [ ]:
def sapxepChen(mang):
  m = np.copy(mang) # Bước 1: Tạo bản sao của mảng input
  i = 1 # Bước 2: Bắt đầu từ phần tử thứ 2 (index 1)
  n = len(m) # Bước 3: Lấy chiều dài của mảng

  while(i < n): # Bước 4: Lặp qua các phần tử từ vị trí thứ 2 đến cuối mảng
    key = m[i] # Bước 5: Lưu giá trị của phần tử cần chèn (key)
    print("key=", key)
    j = i-1 # Bước 6: Chỉ số j được đặt là phần tử ngay trước key
    print("j=", j)
    while j >= 0 and m[j] > key: # Bước 7: Di chuyển các phần tử lớn hơn key sang một vị trí phía sau
      m[j+1] = m[j] # Di chuyển m[j] lên một vị trí
      j-=1 # Giảm j xuống để tiếp tục kiểm tra phần tử trước đó
      print("j= ", j)
    # Bước 8: Chèn key vào vị trí thích hợp
    print(m[j+1])
    m[j+1] = key # Đặt key vào đúng vị trí sau khi các phần tử lớn hơn đã bị di chuyển
    i+=1 # Bước 9: Tiến tới phần tử tiếp theo
    print(*m)
  return m

In [ ]:
a = [4,5,3,2,1,9,7,5]
print(a)
print(sapxepChen(a))

[4, 5, 3, 2, 1, 9, 7, 5]
key= 5
j= 0
5
4 5 3 2 1 9 7 5
key= 3
j= 1
j=  0
j=  -1
4
3 4 5 2 1 9 7 5
key= 2
j= 2
j=  1
j=  0
j=  -1
3
2 3 4 5 1 9 7 5
key= 1
j= 3
j=  2
j=  1
j=  0
j=  -1
2
1 2 3 4 5 9 7 5
key= 9
j= 4
9
1 2 3 4 5 9 7 5
key= 7
j= 5
j=  4
9
1 2 3 4 5 7 9 5
key= 5
j= 6
j=  5
j=  4
7
1 2 3 4 5 5 7 9
[1 2 3 4 5 5 7 9]


# **MERGE SORT**

In [ ]:
#merge sort (sắp xếp tăng dần)
def hopnhat(mleft, mright):
  L = np.copy(mleft)
  R = np.copy(mright)
  i = j = 0
  kq = []
  while(i < len(L) and j < len(R)):
    if(L[i] < R[j]):
      kq.append(L[i])
      i+=1
    else:
      kq.append(R[j])
      j+=1
  while(i <len(L)):
    kq.append(L[i])
    i+=1
  while(j < len(R)):
    kq.append(R[j])
    j+=1
  print(*kq)
  return kq

def sxhn(mang):
  m = np.copy(mang)
  if len(m) <=1:
    return mang
  k = len(m)//2
  L = np.copy(m[:k])
  R = np.copy(m[k:])
  print(L)
  print(R)
  return hopnhat(sxhn(L), sxhn(R))

In [ ]:
a = [4,5,3,2,1,9,7,5]
print(sxhn(a))

[4 5 3 2]
[1 9 7 5]
[4 5]
[3 2]
[4]
[5]
4 5
[3]
[2]
2 3
2 3 4 5
[1 9]
[7 5]
[1]
[9]
1 9
[7]
[5]
5 7
1 5 7 9
1 2 3 4 5 5 7 9
[1, 2, 3, 4, 5, 5, 7, 9]


In [ ]:
#merge sort (sắp xếp giảm dần)
def hopnhat(mleft, mright):
  L = np.copy(mleft)
  R = np.copy(mright)
  i = j = 0
  kq = []
  while(i < len(L) and j < len(R)):
    if(L[i] > R[j]):
      kq.append(L[i])
      i+=1
    else:
      kq.append(R[j])
      j+=1
  while(i <len(L)):
    kq.append(L[i])
    i+=1
  while(j < len(R)):
    kq.append(R[j])
    j+=1
  return kq

def sxhn(mang):
  m = np.copy(mang)
  if len(m) <=1:
    return mang
  k = len(m)//2
  L = np.copy(m[:k])
  R = np.copy(m[k:])
  return hopnhat(sxhn(L), sxhn(R))

In [ ]:
a = [1,2,7,9,8,1,3]

In [ ]:
print(sxhn(a))

[9, 8, 7, 3, 2, 1, 1]


In [ ]:
#xac dinh xem co hay khong 2 phan tu co tong bang mot tong cho truoc hay khong?
def hopnhat(mleft, mright, tong):
  L = np.copy(mleft)
  R = np.copy(mright)
  i = j = 0
  kq = []
  while(i < len(L) and j < len(R)):
    if(L[i] + R[i]==M):
      return True
    elif(L[i] < R[j]):
      kq.append(L[i])
      i+=1
    else:
      kq.append(R[j])
      j+=1
  while(i <len(L)):
    kq.append(L[i])
    i+=1
  while(j < len(R)):
    kq.append(R[j])
    j+=1
  return kq

def sxhn(mang, tong):
  m = np.copy(mang)
  if len(m) <=1:
    return mang
  k = len(m)//2
  L = np.copy(m[:k])
  R = np.copy(m[k:])
  return hopnhat(sxhn(L, tong), sxhn(R, tong), tong)

In [ ]:
a = [1,3,9,2,5]
M = 8
print(sxhn(a, 8))

True


In [ ]:
A = np.random.randint(0, 10000, 10**6)
print(len(A))
sxhn(a, 8)

1000000


True

In [ ]:
import time
t1 = time.time()
sxhn(a, 8)
t2 = time.time()
print(t2-t1)

0.0002472400665283203
